import { vars } from "nativewind";

const colors = {
  default: {
    light: vars({
      "--color-primary-default": "#3a5e96",
      "--color-primary-light": "#5bd1e7",
      "--color-secondary-default": "#9b6cca",
      "--color-secondary-light": "#dfbeff",
      "--color-tertiary-default": "#ff88bd",
      "--color-tertiary-light": "#ffc2e6",
      "--color-accent-default": "#f9c04a",
      "--color-accent-light": "#ffeea9",
      "--color-grey-default": "#979797",
      "--color-slate-default": "#38383a",
      "--color-dark-default": "#000000",
      "--color-light-default": "#ffffff",
      "--color-overlay": "rgba(0, 0, 0, .05)",
      "--color-dark-light": "#000000",
    }),
    dark: vars({
      "--color-primary-default": "#ffffff",
      "--color-primary-light": "#ffffff",
      "--color-secondary-default": "#9b6cca",
      "--color-secondary-light": "#dfbeff",
      "--color-tertiary-default": "#ff88bd",
      "--color-tertiary-light": "#ffc2e6",
      "--color-accent-default": "#f9c04a",
      "--color-accent-light": "#ffeea9",
      "--color-grey-default": "#979797",
      "--color-slate-default": "#38383a",
      "--color-dark-default": "#1f355b",
      "--color-light-default": "#1E1E1E",
      "--color-overlay": "rgba(255, 255, 255, .05)",
      "--color-dark-light": "#ffffff",
    }),
  },
  default2: {
    light: vars({
      "--color-primary-default": "red",
      "--color-primary-light": "#FF474C",
      "--color-secondary-default": "#9b6cca",
      "--color-secondary-light": "#dfbeff",
      "--color-tertiary-default": "#ff88bd",
      "--color-tertiary-light": "#ffc2e6",
      "--color-accent-default": "#f9c04a",
      "--color-accent-light": "#ffeea9",
      "--color-grey-default": "#979797",
      "--color-slate-default": "#38383a",
      "--color-dark-default": "#1f355b",
      "--color-light-default": "#ffffff",
      "--color-overlay": "rgba(0, 0, 0, .05)",
      "--color-dark-light": "#000000",
    }),
    dark: vars({
      "--color-primary-default": "#ffffff",
      "--color-primary-light": "#ffffff",
      "--color-secondary-default": "#9b6cca",
      "--color-secondary-light": "#dfbeff",
      "--color-tertiary-default": "#ff88bd",
      "--color-tertiary-light": "#ffc2e6",
      "--color-accent-default": "#f9c04a",
      "--color-accent-light": "#ffeea9",
      "--color-grey-default": "#979797",
      "--color-slate-default": "#38383a",
      "--color-dark-default": "#1f355b",
      "--color-light-default": "#1E1E1E",
      "--color-overlay": "rgba(255, 255, 255, .05)",
      "--color-dark-light": "#ffffff",
    }),
  },
}

export default colors